import './globals.css'
import { Roboto, Poppins } from 'next/font/google'

export const textFont = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-text'
})

export const displayFont = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100','200', '300', '400', '500','600', '700','800', '900'],
  variable: '--font-display'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={textFont.className + " " + displayFont.className + " " + displayFont.variable + " " + textFont.variable}>{children}</body>
    </html>
  )
}
